disabled_rules:
- trailing_whitespace
- type_name
- multiple_closures_with_trailing_closure
- identifier_name
- large_tuple
- nesting
- opening_brace
- private_over_fileprivate

opt_in_rules:
- empty_count
- empty_string
- explicit_init
- operator_usage_whitespace
- prohibited_super_call
- redundant_nil_coalescing
- sorted_first_last
- contains_over_first_not_nil
- first_where
- implicit_return
- literal_expression_end_indentation
- private_action
- private_outlet

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self
line_length:
    warning: 180
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 500
    error: 600
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
implicit_return:
  included: [closure]
reporter: "xcode"
