//
//  MainTabViewView.swift
//  ImageAI
//
//  Created by Martin Lukacs on 08/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVVM Xcode Templates
//

import Resolver
import SwiftUI
import SwiftUICombineToolBox

struct MainTabView: View {
    @InjectedObject private var viewModel: MainTabViewModel
    @Injected private var router: MainTabNavigation

    var body: some View {
        TabView {
            createTabItem(for: .video)
            createTabItem(for: .photo)
            createTabItem(for: .library)
        }
    }
}

extension MainTabView {
    private func createTabItem(for type: MainTabDestinationType, shouldUpdateOffset: Bool = false) -> some View {
        LazyView(router.goToPage(for: type).embedInNavigation())
            .tabItem {
                Label(MainTabDestinationType.getName(for: type),
                      systemImage: MainTabDestinationType.getIconName(for: type))
            }
            .tag(MainTabDestinationType.getTabNumber(for: type))
    }
}

struct MainTabView_Previews: PreviewProvider {
    static var previews: some View {
        MainTabView()
    }
}
