//
//  MainTabViewViewModel.swift
//  ImageAI
//
//  Created by Martin Lukacs on 08/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//

import Combine
import Foundation
import Resolver

final class MainTabViewModel: ObservableObject {
    // @Injected var router: XXX type of router

    private var cancellables = Set<AnyCancellable>()

    init() {
        setUp()
    }
}

extension MainTabViewModel {
    private func setUp() {}
}
