//
//  ViewModels+Dependencies.swift
//  ImageAI
//
//  Created by Martin Lukacs on 08/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVVM Xcode Templates
//

import Resolver

extension Resolver {
    public static func registerViewModels() {
        register { MainTabViewModel() }.scope(.application)
        register { VideoViewModel() }.scope(.shared)
    }
}
