//
//  VideoView.swift
//  ImageAI
//
//  Created by Martin Lukacs on 08/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVVM Xcode Templates
//

import AVFoundation
import Resolver
import SwiftUI

struct VideoView: View {
    @InjectedObject private var viewModel: VideoViewModel

    var body: some View {
        containerView
            .onAppear {
                viewModel.checkCameraRights()
            }
    }
}

extension VideoView {
    private var containerView: some View {
        ZStack(alignment: Alignment(horizontal: .center, vertical: .bottom)) {
            CameraDisplay(session: viewModel.getCurrentAVSession())
                .ignoresSafeArea(.all, edges: .all)

            Text("Just to try")
                .frame(width: 100, height: 50)
                .background(Color.gray)
                .cornerRadius(5)
                .padding()
        }
    }
}

struct VideoView_Previews: PreviewProvider {
    static var previews: some View {
        VideoView()
    }
}

struct CameraDisplay: UIViewRepresentable {
    var session: AVCaptureSession

    func makeUIView(context: Context) -> UIView {
        let view = UIView(frame: UIScreen.main.bounds)
        let videoDisplay = AVCaptureVideoPreviewLayer(session: session)
        videoDisplay.frame = view.frame
        videoDisplay.videoGravity = .resizeAspectFill
        view.layer.addSublayer(videoDisplay)
        return view
    }

    func updateUIView(_ uiView: UIView, context: Context) {}
}
